name: Lint

# We ignore the dangerous-triggers warning because forked PRs
# require repo secrets to run some of the defined checks,
# and we protect against malicious actors by requiring approval
# for all external contributors before workflows will run.
on: pull_request_target # zizmor: ignore[dangerous-triggers]

concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.ref }}
  cancel-in-progress: true

permissions: {}

jobs:
  lint:
    uses: masterpointio/actions/.github/workflows/lint.yaml@dc403c87226db5bac0f18d0dcdd99c305d864472 #v0.1.0
    secrets:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
