name: Release Please

on:
  push:
    branches:
      - main

concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.ref }}
  cancel-in-progress: true

permissions: {}

jobs:
  release-please:
    uses: masterpointio/actions/.github/workflows/release-please.yaml@02a3436b35718208185b3eaa90139c8c395f3f40
    with:
      release-type: terraform-module
    secrets:
      MP_BOT_APP_ID: ${{ secrets.MP_BOT_APP_ID }}
      MP_BOT_APP_PRIVATE_KEY: ${{ secrets.MP_BOT_APP_PRIVATE_KEY }}
