name: TF Test

on:
  push:
    branches:
      - main
  # We ignore the dangerous-triggers warning because forked PRs
  # require repo secrets to run some of the defined checks,
  # and we protect against malicious actors by requiring approval
  # for all external contributors before workflows will run.
  pull_request_target: # zizmor: ignore[dangerous-triggers]

concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.ref }}
  cancel-in-progress: true

permissions: {}

jobs:
  tf-test:
    uses: masterpointio/actions/.github/workflows/test.yaml@dc403c87226db5bac0f18d0dcdd99c305d864472 #v0.1.0
    with:
      aws_role_arn: ${{ vars.TF_TEST_AWS_ROLE_ARN }}
    secrets:
      SPACELIFT_API_KEY_ENDPOINT: ${{ secrets.SPACELIFT_API_KEY_ENDPOINT }}
      SPACELIFT_API_KEY_ID: ${{ secrets.SPACELIFT_API_KEY_ID }}
      SPACELIFT_API_KEY_SECRET: ${{ secrets.SPACELIFT_API_KEY_SECRET }}
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
