name: TF Test

on:
  push:
    branches:
      - main
  pull_request_target:

permissions:
  actions: read
  checks: write
  contents: read
  id-token: write
  pull-requests: read

jobs:
  tf-test:
    name: 🧪 ${{ matrix.tf }} test
    runs-on: ubuntu-latest
    strategy:
      matrix:
        tf: [tofu, terraform]
    steps:

      - name: Install Aqua
        uses: aquaproj/aqua-installer@v4.0.4
        with:
          aqua_version: v2.48.1
