name: Trunk Upgrade

on:
  schedule:
    # On the first day of every month @ 8am
    - cron: 0 8 1 * *
  workflow_dispatch: {}

permissions: read-all

jobs:
  trunk-upgrade:
    runs-on: ubuntu-latest
    permissions:
      # For trunk to create PRs
      contents: write
      pull-requests: write
    steps:
      - name: Checkout
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2

      - name: Run Trunk Upgrade
        uses: masterpointio/github-action-trunk-upgrade@v0.1.0
        with:
          app-id: ${{ secrets.MP_BOT_APP_ID }}
          app-private-key: ${{ secrets.MP_BOT_APP_PRIVATE_KEY }}
          github-token: ${{ secrets.MASTERPOINT_TEAM_PAT }}
          reviewers: "@masterpointio/masterpoint-open-source"
