name: Trunk Upgrade

on:
  schedule:
    # On the first day of every month @ 8am
    - cron: 0 8 1 * *
  workflow_dispatch: {}

concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.ref }}
  cancel-in-progress: true

permissions: {}

jobs:
  trunk-upgrade:
    uses: masterpointio/actions/.github/workflows/trunk-upgrade.yaml@dc403c87226db5bac0f18d0dcdd99c305d864472 #v0.1.0
    secrets:
      MP_BOT_APP_ID: ${{ secrets.MP_BOT_APP_ID }}
      MP_BOT_APP_PRIVATE_KEY: ${{ secrets.MP_BOT_APP_PRIVATE_KEY }}
      MASTERPOINT_TEAM_PAT: ${{ secrets.MASTERPOINT_TEAM_PAT }}
