name: Zizmor

on:
  push:
    branches:
      - main
  pull_request:

concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.ref }}
  cancel-in-progress: true

permissions: {}

jobs:
  zizmor:
    uses: masterpointio/actions/.github/workflows/zizmor.yaml@dc403c87226db5bac0f18d0dcdd99c305d864472 #v0.1.0
